- name: variable to print
  hosts: web
  vars:
    course: "Devops with aws"
    duration: "12 hr"
    trainer: "god"
    vars_files:
  - vars.yaml
  vars_prompt:
  - name: course
    prompt: please enter the course name
    private: false
  tasks:
  - name: print the information
    vars:
    course: "Devops with aws from task level"
    duratio: "1hr"
    trainer: "rajesh"
    ansible.builtin.debug:
      msg: "hi, i am learning {{course}} with duratio is {{duration}} and trainer is {{trainer}}"
