- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user exits or not
    ansible.builtin.command: id Rajesh
    register: USER
    ignore_errors: true

  - name: print the user information
    ansible.builtin.debug:
      msg: "user information: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd Rajesh
    when: USER.rc !=0