- name: packages installing using loops concept
  hosts: web
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      msg: "{{ item }} "
    loop:
    - msql
    - nginx
    - postfix
    - httpd