- name: packages installing using loops concept
  hosts: web
  become: yes
  tasks:
  - name: print name
    ansible.builtin.package:
      name: "{{ item }} "
      state: present
    loop:
    - msql
    - nginx
    - postfix
    - httpd