- name: demo on filters
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "hello, {{ course | default('ansible') }}"

  - name: convert to uppercase
    vars:
     greetings: "hello rajesh"
    ansible.builtin.debug:
     msg: "{{ greetings | upper }}"

  - name: convert to lowercase
    vars:
     greetings: "HELLO RAJESH"
    ansible.builtin.debug:
     msg: "{{ greetings | lower }}"