- name: variables to print
  hosts: web
  vars:
    course: "DevOps with AWS"
    Duration: "120 HRS"
    Trainer: "Rajesh"
  tasks:
  - name: print the information
    ansible.builtin.debug;
    msg: "Hello, I am learnin course is:{{ course }}, Duration is :{{ Duration }}, Trainer is :{{ Trainer }}"