- name: variables from file
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the information
    ansible.builtin.deubug:
      msg: 'Hi, I am printing the information of course={{course}}, duration={{duration}}, trainer={{trainer}}'
