- name: variables from file
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the course information
    ansible.builtin.deubug:
      msg:"Hi Printing the course={{course}}, duration={{duration}}, trainer={{trainer}}"
